controllers:
    resource: ../src/Controller/
    type: attribute

contactoFicha:
    path: /contacto/{codigo}
    controller: ../src/Controller/ContactoController::ficha

contactoBuscar:
    path: /contacto/buscar/{texto}
    controller: ../src/Controller/ContactoController::buscar